
POST localhost:8080/api/movies
content-type: application/json

{
    "title": "The Godfather"
}

###
GET localhost:8080/api/movies

###
GET localhost:8080/api/screenings
content-type: application/json
{
   "movieId": 1,
}
###
GET localhost:8080/api/movies
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0IiwiaWF0IjoxNjgzNzQ3MzU4LCJleHAiOjE2ODM3ODMzNTh9.qve_GU8ZBExGWXb8NcoEdt59CJVcP85tBQkFwZmhcmc



###
GET localhost:8080/api/movies/1

###
GET localhost:8080/api/screenings?movieId=6

###
GET localhost:8080/api/screenings

###
GET localhost:8080/demo-controller
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlIiwiaWF0IjoxNjgzNzMwOTYzLCJleHAiOjE2ODM3NjY5NjN9.-9n0J6R-IROiysKT3Q4m1dyu_Ofz_87vuG5U0BXm-tk


###
POST localhost:8080/api/auth/register
content-type: application/json

{
    "email": "pp",
    "password": "password",
      "name": "name",
      "surname": "surname"

}

###
POST localhost:8080/api/auth/login
content-type: application/json

{
    "email": "pp",
    "password": "password"
}

###
GET localhost:8080/logged/user
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnb3NpYXh4eEBnbWFpbC5jb20iLCJpYXQiOjE2ODQ5NTc3NDEsImV4cCI6MTY4NDk5Mzc0MX0.jKK1Ap7hSv-F91VtZKp9MfR8OnI6EbXm6ZXdknlyY5c



###
GET localhost:8080/logged/place-order

###

GET localhost:8080/api/authors
